name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Test & build
    runs-on: ubuntu-latest
    steps:
    
    - name: Install dependencies
      run: apt update && apt-get -y install openssl

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .
    
    - name: Create test-dependencies
      run: make create-test-certs

    - name: Test
      run: go test -v ./...
    
    - name: Cleanup after tests
      run: make clean-test-ca

